# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/blog/posts/2023-10-01-hello-blog/index.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/blog/posts/2023-10-01-hello-blog/index.ipynb 3
def foo(): pass
